export const italianCities: {
  id: number;
  name: string;
  slug: string;
  region: string | null;
  province: string | null;
  provinceCode: string | null;
  lat: number | null;
  lng: number | null;
  altNames: string[];
  isActive: boolean;
  sortOrder: number | null;
}[] = [
  {
    id: 1,
    name: 'Rome',
    slug: 'rome',
    region: 'Lazio',
    province: 'Roma',
    provinceCode: 'RM',
    lat: 41.902782,
    lng: 12.496366,
    altNames: ['Roma'],
    isActive: true,
    sortOrder: 1,
  },
  {
    id: 2,
    name: 'Milan',
    slug: 'milan',
    region: 'Lombardia',
    province: 'Milano',
    provinceCode: 'MI',
    lat: 45.464203,
    lng: 9.189982,
    altNames: ['Milano'],
    isActive: true,
    sortOrder: 2,
  },
  {
    id: 3,
    name: 'Naples',
    slug: 'naples',
    region: 'Campania',
    province: 'Napoli',
    provinceCode: 'NA',
    lat: 40.851774,
    lng: 14.268124,
    altNames: ['Napoli'],
    isActive: true,
    sortOrder: 3,
  },
  {
    id: 4,
    name: 'Turin',
    slug: 'turin',
    region: 'Piemonte',
    province: 'Torino',
    provinceCode: 'TO',
    lat: 45.070339,
    lng: 7.686864,
    altNames: ['Torino'],
    isActive: true,
    sortOrder: 4,
  },
  {
    id: 5,
    name: 'Palermo',
    slug: 'palermo',
    region: 'Sicilia',
    province: 'Palermo',
    provinceCode: 'PA',
    lat: 38.115686,
    lng: 13.361267,
    altNames: [],
    isActive: true,
    sortOrder: 5,
  },
  {
    id: 6,
    name: 'Genoa',
    slug: 'genoa',
    region: 'Liguria',
    province: 'Genova',
    provinceCode: 'GE',
    lat: 44.405645,
    lng: 8.946256,
    altNames: ['Genova'],
    isActive: true,
    sortOrder: 6,
  },
  {
    id: 7,
    name: 'Bologna',
    slug: 'bologna',
    region: 'Emilia-Romagna',
    province: 'Bologna',
    provinceCode: 'BO',
    lat: 44.494887,
    lng: 11.342616,
    altNames: [],
    isActive: true,
    sortOrder: 7,
  },
  {
    id: 8,
    name: 'Florence',
    slug: 'florence',
    region: 'Toscana',
    province: 'Firenze',
    provinceCode: 'FI',
    lat: 43.76956,
    lng: 11.255814,
    altNames: ['Firenze'],
    isActive: true,
    sortOrder: 8,
  },
  {
    id: 9,
    name: 'Bari',
    slug: 'bari',
    region: 'Puglia',
    province: 'Bari',
    provinceCode: 'BA',
    lat: 41.117143,
    lng: 16.871871,
    altNames: [],
    isActive: true,
    sortOrder: 9,
  },
  {
    id: 10,
    name: 'Catania',
    slug: 'catania',
    region: 'Sicilia',
    province: 'Catania',
    provinceCode: 'CT',
    lat: 37.507877,
    lng: 15.08303,
    altNames: [],
    isActive: true,
    sortOrder: 10,
  },
  {
    id: 11,
    name: 'Venice',
    slug: 'venice',
    region: 'Veneto',
    province: 'Venezia',
    provinceCode: 'VE',
    lat: 45.440847,
    lng: 12.315515,
    altNames: ['Venezia'],
    isActive: true,
    sortOrder: 11,
  },
  {
    id: 12,
    name: 'Verona',
    slug: 'verona',
    region: 'Veneto',
    province: 'Verona',
    provinceCode: 'VR',
    lat: 45.438384,
    lng: 10.991622,
    altNames: [],
    isActive: true,
    sortOrder: 12,
  },
  {
    id: 13,
    name: 'Messina',
    slug: 'messina',
    region: 'Sicilia',
    province: 'Messina',
    provinceCode: 'ME',
    lat: 38.193813,
    lng: 15.554126,
    altNames: [],
    isActive: true,
    sortOrder: 13,
  },
  {
    id: 14,
    name: 'Padua',
    slug: 'padua',
    region: 'Veneto',
    province: 'Padova',
    provinceCode: 'PD',
    lat: 45.406434,
    lng: 11.876761,
    altNames: ['Padova'],
    isActive: true,
    sortOrder: 14,
  },
  {
    id: 15,
    name: 'Trieste',
    slug: 'trieste',
    region: 'Friuli-Venezia Giulia',
    province: 'Trieste',
    provinceCode: 'TS',
    lat: 45.649523,
    lng: 13.776818,
    altNames: [],
    isActive: true,
    sortOrder: 15,
  },
  {
    id: 16,
    name: 'Taranto',
    slug: 'taranto',
    region: 'Puglia',
    province: 'Taranto',
    provinceCode: 'TA',
    lat: 40.464667,
    lng: 17.247945,
    altNames: [],
    isActive: true,
    sortOrder: 16,
  },
  {
    id: 17,
    name: 'Brescia',
    slug: 'brescia',
    region: 'Lombardia',
    province: 'Brescia',
    provinceCode: 'BS',
    lat: 45.5392,
    lng: 10.22,
    altNames: [],
    isActive: true,
    sortOrder: 17,
  },
  {
    id: 18,
    name: 'Prato',
    slug: 'prato',
    region: 'Toscana',
    province: 'Prato',
    provinceCode: 'PO',
    lat: 43.877717,
    lng: 11.102172,
    altNames: [],
    isActive: true,
    sortOrder: 18,
  },
  {
    id: 19,
    name: 'Reggio Calabria',
    slug: 'reggio-calabria',
    region: 'Calabria',
    province: 'Reggio di Calabria',
    provinceCode: 'RC',
    lat: 38.1144,
    lng: 15.65,
    altNames: ['Reggio di Calabria'],
    isActive: true,
    sortOrder: 19,
  },
  {
    id: 20,
    name: 'Modena',
    slug: 'modena',
    region: 'Emilia-Romagna',
    province: 'Modena',
    provinceCode: 'MO',
    lat: 44.647128,
    lng: 10.925227,
    altNames: [],
    isActive: true,
    sortOrder: 20,
  },
  {
    id: 21,
    name: 'Reggio Emilia',
    slug: 'reggio-emilia',
    region: 'Emilia-Romagna',
    province: 'Reggio Emilia',
    provinceCode: 'RE',
    lat: 44.698612,
    lng: 10.62981,
    altNames: [],
    isActive: true,
    sortOrder: 21,
  },
  {
    id: 22,
    name: 'Perugia',
    slug: 'perugia',
    region: 'Umbria',
    province: 'Perugia',
    provinceCode: 'PG',
    lat: 43.110717,
    lng: 12.390827,
    altNames: [],
    isActive: true,
    sortOrder: 22,
  },
  {
    id: 23,
    name: 'Ravenna',
    slug: 'ravenna',
    region: 'Emilia-Romagna',
    province: 'Ravenna',
    provinceCode: 'RA',
    lat: 44.417326,
    lng: 12.203865,
    altNames: [],
    isActive: true,
    sortOrder: 23,
  },
  {
    id: 24,
    name: 'Livorno',
    slug: 'livorno',
    region: 'Toscana',
    province: 'Livorno',
    provinceCode: 'LI',
    lat: 43.5485,
    lng: 10.3106,
    altNames: ['Leghorn'],
    isActive: true,
    sortOrder: 24,
  },
  {
    id: 25,
    name: 'Cagliari',
    slug: 'cagliari',
    region: 'Sardegna',
    province: 'Cagliari',
    provinceCode: 'CA',
    lat: 39.22384,
    lng: 9.121661,
    altNames: [],
    isActive: true,
    sortOrder: 25,
  },
  {
    id: 26,
    name: 'Foggia',
    slug: 'foggia',
    region: 'Puglia',
    province: 'Foggia',
    provinceCode: 'FG',
    lat: 41.462223,
    lng: 15.544372,
    altNames: [],
    isActive: true,
    sortOrder: 26,
  },
  {
    id: 27,
    name: 'Rimini',
    slug: 'rimini',
    region: 'Emilia-Romagna',
    province: 'Rimini',
    provinceCode: 'RN',
    lat: 44.0678,
    lng: 12.5695,
    altNames: [],
    isActive: true,
    sortOrder: 27,
  },
  {
    id: 28,
    name: 'Salerno',
    slug: 'salerno',
    region: 'Campania',
    province: 'Salerno',
    provinceCode: 'SA',
    lat: 40.6801,
    lng: 14.7594,
    altNames: [],
    isActive: true,
    sortOrder: 28,
  },
  {
    id: 29,
    name: 'Ferrara',
    slug: 'ferrara',
    region: 'Emilia-Romagna',
    province: 'Ferrara',
    provinceCode: 'FE',
    lat: 44.8354,
    lng: 11.6198,
    altNames: [],
    isActive: true,
    sortOrder: 29,
  },
  {
    id: 30,
    name: 'Sassari',
    slug: 'sassari',
    region: 'Sardegna',
    province: 'Sassari',
    provinceCode: 'SS',
    lat: 40.727222,
    lng: 8.559722,
    altNames: [],
    isActive: true,
    sortOrder: 30,
  },
  {
    id: 31,
    name: 'Latina',
    slug: 'latina',
    region: 'Lazio',
    province: 'Latina',
    provinceCode: 'LT',
    lat: 41.4669,
    lng: 12.9037,
    altNames: [],
    isActive: true,
    sortOrder: 31,
  },
  {
    id: 32,
    name: 'Giugliano in Campania',
    slug: 'giugliano-in-campania',
    region: 'Campania',
    province: 'Napoli',
    provinceCode: 'NA',
    lat: 40.9363,
    lng: 14.1978,
    altNames: [],
    isActive: true,
    sortOrder: 32,
  },
  {
    id: 33,
    name: 'Monza',
    slug: 'monza',
    region: 'Lombardia',
    province: 'Monza e Brianza',
    provinceCode: 'MB',
    lat: 45.5845,
    lng: 9.2744,
    altNames: [],
    isActive: true,
    sortOrder: 33,
  },
  {
    id: 34,
    name: 'Siracusa',
    slug: 'siracusa',
    region: 'Sicilia',
    province: 'Siracusa',
    provinceCode: 'SR',
    lat: 37.075474,
    lng: 15.286586,
    altNames: ['Syracuse'],
    isActive: true,
    sortOrder: 34,
  },
  {
    id: 35,
    name: 'Pescara',
    slug: 'pescara',
    region: 'Abruzzo',
    province: 'Pescara',
    provinceCode: 'PE',
    lat: 42.461,
    lng: 14.2161,
    altNames: [],
    isActive: true,
    sortOrder: 35,
  },
  {
    id: 36,
    name: 'Bergamo',
    slug: 'bergamo',
    region: 'Lombardia',
    province: 'Bergamo',
    provinceCode: 'BG',
    lat: 45.698334,
    lng: 9.677274,
    altNames: [],
    isActive: true,
    sortOrder: 36,
  },
  {
    id: 37,
    name: 'Forlì',
    slug: 'forl',
    region: 'Emilia-Romagna',
    province: 'Forlì-Cesena',
    provinceCode: 'FC',
    lat: 44.2225,
    lng: 12.04,
    altNames: [],
    isActive: true,
    sortOrder: 37,
  },
  {
    id: 38,
    name: 'Trento',
    slug: 'trento',
    region: 'Trentino-Alto Adige',
    province: 'Trento',
    provinceCode: 'TN',
    lat: 46.0667,
    lng: 11.1197,
    altNames: [],
    isActive: true,
    sortOrder: 38,
  },
  {
    id: 39,
    name: 'Vicenza',
    slug: 'vicenza',
    region: 'Veneto',
    province: 'Vicenza',
    provinceCode: 'VI',
    lat: 45.5455,
    lng: 11.5354,
    altNames: [],
    isActive: true,
    sortOrder: 39,
  },
  {
    id: 40,
    name: 'Terni',
    slug: 'terni',
    region: 'Umbria',
    province: 'Terni',
    provinceCode: 'TR',
    lat: 42.5626,
    lng: 12.6427,
    altNames: [],
    isActive: true,
    sortOrder: 40,
  },
  {
    id: 41,
    name: 'Bolzano',
    slug: 'bolzano',
    region: 'Trentino-Alto Adige',
    province: 'Bolzano',
    provinceCode: 'BZ',
    lat: 46.4983,
    lng: 11.3548,
    altNames: ['Bozen'],
    isActive: true,
    sortOrder: 41,
  },
  {
    id: 42,
    name: 'Novara',
    slug: 'novara',
    region: 'Piemonte',
    province: 'Novara',
    provinceCode: 'NO',
    lat: 45.4459,
    lng: 8.6222,
    altNames: [],
    isActive: true,
    sortOrder: 42,
  },
  {
    id: 43,
    name: 'Piacenza',
    slug: 'piacenza',
    region: 'Emilia-Romagna',
    province: 'Piacenza',
    provinceCode: 'PC',
    lat: 45.0524,
    lng: 9.6929,
    altNames: [],
    isActive: true,
    sortOrder: 43,
  },
  {
    id: 44,
    name: 'Ancona',
    slug: 'ancona',
    region: 'Marche',
    province: 'Ancona',
    provinceCode: 'AN',
    lat: 43.615829,
    lng: 13.518894,
    altNames: [],
    isActive: true,
    sortOrder: 44,
  },
  {
    id: 45,
    name: 'Lecce',
    slug: 'lecce',
    region: 'Puglia',
    province: 'Lecce',
    provinceCode: 'LE',
    lat: 40.351516,
    lng: 18.175023,
    altNames: [],
    isActive: true,
    sortOrder: 45,
  },
  {
    id: 46,
    name: 'Andria',
    slug: 'andria',
    region: 'Puglia',
    province: 'Barletta-Andria-Trani',
    provinceCode: 'BT',
    lat: 41.23128,
    lng: 16.30836,
    altNames: [],
    isActive: true,
    sortOrder: 46,
  },
  {
    id: 47,
    name: 'Udine',
    slug: 'udine',
    region: 'Friuli-Venezia Giulia',
    province: 'Udine',
    provinceCode: 'UD',
    lat: 46.0713,
    lng: 13.234,
    altNames: [],
    isActive: true,
    sortOrder: 47,
  },
  {
    id: 48,
    name: 'Arezzo',
    slug: 'arezzo',
    region: 'Toscana',
    province: 'Arezzo',
    provinceCode: 'AR',
    lat: 43.4633,
    lng: 11.8798,
    altNames: [],
    isActive: true,
    sortOrder: 48,
  },
  {
    id: 49,
    name: 'Cesena',
    slug: 'cesena',
    region: 'Emilia-Romagna',
    province: 'Forlì-Cesena',
    provinceCode: 'FC',
    lat: 44.14,
    lng: 12.2438,
    altNames: [],
    isActive: true,
    sortOrder: 49,
  },
  {
    id: 50,
    name: 'La Spezia',
    slug: 'la-spezia',
    region: 'Liguria',
    province: 'La Spezia',
    provinceCode: 'SP',
    lat: 44.1025,
    lng: 9.8289,
    altNames: [],
    isActive: true,
    sortOrder: 50,
  },
  {
    id: 51,
    name: 'Alessandria',
    slug: 'alessandria',
    region: 'Piemonte',
    province: 'Alessandria',
    provinceCode: 'AL',
    lat: 44.9125,
    lng: 8.615,
    altNames: [],
    isActive: true,
    sortOrder: 51,
  },
  {
    id: 52,
    name: 'Pesaro',
    slug: 'pesaro',
    region: 'Marche',
    province: 'Pesaro e Urbino',
    provinceCode: 'PU',
    lat: 43.909,
    lng: 12.9054,
    altNames: [],
    isActive: true,
    sortOrder: 52,
  },
  {
    id: 53,
    name: 'Barletta',
    slug: 'barletta',
    region: 'Puglia',
    province: 'Barletta-Andria-Trani',
    provinceCode: 'BT',
    lat: 41.3186,
    lng: 16.2819,
    altNames: [],
    isActive: true,
    sortOrder: 53,
  },
  {
    id: 54,
    name: 'Pistoia',
    slug: 'pistoia',
    region: 'Toscana',
    province: 'Pistoia',
    provinceCode: 'PT',
    lat: 43.9358,
    lng: 10.914,
    altNames: [],
    isActive: true,
    sortOrder: 54,
  },
  {
    id: 55,
    name: 'Lucca',
    slug: 'lucca',
    region: 'Toscana',
    province: 'Lucca',
    provinceCode: 'LU',
    lat: 43.8447,
    lng: 10.5027,
    altNames: [],
    isActive: true,
    sortOrder: 55,
  },
  {
    id: 56,
    name: 'Catanzaro',
    slug: 'catanzaro',
    region: 'Calabria',
    province: 'Catanzaro',
    provinceCode: 'CZ',
    lat: 38.9058,
    lng: 16.5944,
    altNames: [],
    isActive: true,
    sortOrder: 56,
  },
  {
    id: 57,
    name: 'Brindisi',
    slug: 'brindisi',
    region: 'Puglia',
    province: 'Brindisi',
    provinceCode: 'BR',
    lat: 40.6401,
    lng: 17.947,
    altNames: [],
    isActive: true,
    sortOrder: 57,
  },
  {
    id: 58,
    name: 'Treviso',
    slug: 'treviso',
    region: 'Veneto',
    province: 'Treviso',
    provinceCode: 'TV',
    lat: 45.6667,
    lng: 12.2414,
    altNames: [],
    isActive: true,
    sortOrder: 58,
  },
  {
    id: 59,
    name: 'Guidonia Montecelio',
    slug: 'guidonia-montecelio',
    region: 'Lazio',
    province: 'Roma',
    provinceCode: 'RM',
    lat: 41.9686,
    lng: 12.682,
    altNames: [],
    isActive: true,
    sortOrder: 59,
  },
  {
    id: 60,
    name: 'Como',
    slug: 'como',
    region: 'Lombardia',
    province: 'Como',
    provinceCode: 'CO',
    lat: 45.8081,
    lng: 9.0852,
    altNames: [],
    isActive: true,
    sortOrder: 60,
  },
  {
    id: 61,
    name: 'Torre del Greco',
    slug: 'torre-del-greco',
    region: 'Campania',
    province: 'Napoli',
    provinceCode: 'NA',
    lat: 40.7628,
    lng: 14.4271,
    altNames: [],
    isActive: true,
    sortOrder: 61,
  },
  {
    id: 62,
    name: 'Busto Arsizio',
    slug: 'busto-arsizio',
    region: 'Lombardia',
    province: 'Varese',
    provinceCode: 'VA',
    lat: 45.6074,
    lng: 8.8473,
    altNames: [],
    isActive: true,
    sortOrder: 62,
  },
  {
    id: 63,
    name: 'Marsala',
    slug: 'marsala',
    region: 'Sicilia',
    province: 'Trapani',
    provinceCode: 'TP',
    lat: 37.8028,
    lng: 12.4345,
    altNames: [],
    isActive: true,
    sortOrder: 63,
  },
  {
    id: 64,
    name: 'Varese',
    slug: 'varese',
    region: 'Lombardia',
    province: 'Varese',
    provinceCode: 'VA',
    lat: 45.82,
    lng: 8.8256,
    altNames: [],
    isActive: true,
    sortOrder: 64,
  },
  {
    id: 65,
    name: 'Sesto San Giovanni',
    slug: 'sesto-san-giovanni',
    region: 'Lombardia',
    province: 'Milano',
    provinceCode: 'MI',
    lat: 45.544,
    lng: 9.221,
    altNames: [],
    isActive: true,
    sortOrder: 65,
  },
  {
    id: 66,
    name: 'Casoria',
    slug: 'casoria',
    region: 'Campania',
    province: 'Napoli',
    provinceCode: 'NA',
    lat: 40.8881,
    lng: 14.3087,
    altNames: [],
    isActive: true,
    sortOrder: 66,
  },
  {
    id: 67,
    name: 'Asti',
    slug: 'asti',
    region: 'Piemonte',
    province: 'Asti',
    provinceCode: 'AT',
    lat: 44.9,
    lng: 8.2065,
    altNames: [],
    isActive: true,
    sortOrder: 67,
  },
  {
    id: 68,
    name: 'Cinisello Balsamo',
    slug: 'cinisello-balsamo',
    region: 'Lombardia',
    province: 'Milano',
    provinceCode: 'MI',
    lat: 45.5449,
    lng: 9.2302,
    altNames: [],
    isActive: true,
    sortOrder: 68,
  },
  {
    id: 69,
    name: 'Gela',
    slug: 'gela',
    region: 'Sicilia',
    province: 'Caltanissetta',
    provinceCode: 'CL',
    lat: 37.0754,
    lng: 14.246,
    altNames: [],
    isActive: true,
    sortOrder: 69,
  },
  {
    id: 70,
    name: 'Cremona',
    slug: 'cremona',
    region: 'Lombardia',
    province: 'Cremona',
    provinceCode: 'CR',
    lat: 45.1333,
    lng: 10.0227,
    altNames: [],
    isActive: true,
    sortOrder: 70,
  },
  {
    id: 71,
    name: 'L\u2019Aquila',
    slug: 'laquila',
    region: 'Abruzzo',
    province: "L'Aquila",
    provinceCode: 'AQ',
    lat: 42.3495,
    lng: 13.3995,
    altNames: ['Aquila'],
    isActive: true,
    sortOrder: 71,
  },
  {
    id: 72,
    name: 'Carpi',
    slug: 'carpi',
    region: 'Emilia-Romagna',
    province: 'Modena',
    provinceCode: 'MO',
    lat: 44.7705,
    lng: 10.8856,
    altNames: [],
    isActive: true,
    sortOrder: 72,
  },
  {
    id: 73,
    name: 'Ragusa',
    slug: 'ragusa',
    region: 'Sicilia',
    province: 'Ragusa',
    provinceCode: 'RG',
    lat: 36.925,
    lng: 14.7164,
    altNames: [],
    isActive: true,
    sortOrder: 73,
  },
  {
    id: 74,
    name: 'Trapani',
    slug: 'trapani',
    region: 'Sicilia',
    province: 'Trapani',
    provinceCode: 'TP',
    lat: 38.0171,
    lng: 12.5136,
    altNames: [],
    isActive: true,
    sortOrder: 74,
  },
  {
    id: 75,
    name: 'Pavia',
    slug: 'pavia',
    region: 'Lombardia',
    province: 'Pavia',
    provinceCode: 'PV',
    lat: 45.186,
    lng: 9.159,
    altNames: [],
    isActive: true,
    sortOrder: 75,
  },
  {
    id: 76,
    name: 'Altamura',
    slug: 'altamura',
    region: 'Puglia',
    province: 'Bari',
    provinceCode: 'BA',
    lat: 40.8084,
    lng: 16.5538,
    altNames: [],
    isActive: true,
    sortOrder: 76,
  },
  {
    id: 77,
    name: 'Massa',
    slug: 'massa',
    region: 'Toscana',
    province: 'Massa-Carrara',
    provinceCode: 'MS',
    lat: 44.035,
    lng: 10.141,
    altNames: [],
    isActive: true,
    sortOrder: 77,
  },
  {
    id: 78,
    name: 'Imola',
    slug: 'imola',
    region: 'Emilia-Romagna',
    province: 'Bologna',
    provinceCode: 'BO',
    lat: 44.3572,
    lng: 11.7167,
    altNames: [],
    isActive: true,
    sortOrder: 78,
  },
  {
    id: 79,
    name: 'Lamezia Terme',
    slug: 'lamezia-terme',
    region: 'Calabria',
    province: 'Catanzaro',
    provinceCode: 'CZ',
    lat: 38.9583,
    lng: 16.3169,
    altNames: [],
    isActive: true,
    sortOrder: 79,
  },
  {
    id: 80,
    name: 'Carrara',
    slug: 'carrara',
    region: 'Toscana',
    province: 'Massa-Carrara',
    provinceCode: 'MS',
    lat: 44.0704,
    lng: 10.1021,
    altNames: [],
    isActive: true,
    sortOrder: 80,
  },
  {
    id: 81,
    name: 'Cosenza',
    slug: 'cosenza',
    region: 'Calabria',
    province: 'Cosenza',
    provinceCode: 'CS',
    lat: 39.2986,
    lng: 16.2538,
    altNames: [],
    isActive: true,
    sortOrder: 81,
  },
  {
    id: 82,
    name: 'Potenza',
    slug: 'potenza',
    region: 'Basilicata',
    province: 'Potenza',
    provinceCode: 'PZ',
    lat: 40.6394,
    lng: 15.8051,
    altNames: [],
    isActive: true,
    sortOrder: 82,
  },
  {
    id: 83,
    name: 'Castellammare di Stabia',
    slug: 'castellammare-di-stabia',
    region: 'Campania',
    province: 'Napoli',
    provinceCode: 'NA',
    lat: 40.7088,
    lng: 14.495,
    altNames: [],
    isActive: true,
    sortOrder: 83,
  },
  {
    id: 84,
    name: 'Molfetta',
    slug: 'molfetta',
    region: 'Puglia',
    province: 'Bari',
    provinceCode: 'BA',
    lat: 41.2241,
    lng: 16.5946,
    altNames: [],
    isActive: true,
    sortOrder: 84,
  },
  {
    id: 85,
    name: 'Viterbo',
    slug: 'viterbo',
    region: 'Lazio',
    province: 'Viterbo',
    provinceCode: 'VT',
    lat: 42.4202,
    lng: 12.1068,
    altNames: [],
    isActive: true,
    sortOrder: 85,
  },
  {
    id: 86,
    name: 'Vigevano',
    slug: 'vigevano',
    region: 'Lombardia',
    province: 'Pavia',
    provinceCode: 'PV',
    lat: 45.318,
    lng: 8.865,
    altNames: [],
    isActive: true,
    sortOrder: 86,
  },
  {
    id: 87,
    name: 'Rozzano',
    slug: 'rozzano',
    region: 'Lombardia',
    province: 'Milano',
    provinceCode: 'MI',
    lat: 45.4,
    lng: 9.1278,
    altNames: [],
    isActive: true,
    sortOrder: 87,
  },
  {
    id: 88,
    name: 'Afragola',
    slug: 'afragola',
    region: 'Campania',
    province: 'Napoli',
    provinceCode: 'NA',
    lat: 40.9043,
    lng: 14.3411,
    altNames: [],
    isActive: true,
    sortOrder: 88,
  },
  {
    id: 89,
    name: "Quartu Sant'Elena",
    slug: 'quartu-sant-elena',
    region: 'Sardegna',
    province: 'Cagliari',
    provinceCode: 'CA',
    lat: 39.2256,
    lng: 9.1746,
    altNames: ['Quartu'],
    isActive: true,
    sortOrder: 89,
  },
  {
    id: 90,
    name: 'Scandicci',
    slug: 'scandicci',
    region: 'Toscana',
    province: 'Firenze',
    provinceCode: 'FI',
    lat: 43.7618,
    lng: 11.1984,
    altNames: [],
    isActive: true,
    sortOrder: 90,
  },
  {
    id: 91,
    name: 'Collegno',
    slug: 'collegno',
    region: 'Piemonte',
    province: 'Torino',
    provinceCode: 'TO',
    lat: 45.0512,
    lng: 7.5723,
    altNames: [],
    isActive: true,
    sortOrder: 91,
  },
  {
    id: 92,
    name: 'Vercelli',
    slug: 'vercelli',
    region: 'Piemonte',
    province: 'Vercelli',
    provinceCode: 'VC',
    lat: 45.3236,
    lng: 8.4231,
    altNames: [],
    isActive: true,
    sortOrder: 92,
  },
  {
    id: 93,
    name: 'Civitavecchia',
    slug: 'civitavecchia',
    region: 'Lazio',
    province: 'Roma',
    provinceCode: 'RM',
    lat: 42.0924,
    lng: 11.795,
    altNames: [],
    isActive: true,
    sortOrder: 93,
  },
  {
    id: 94,
    name: 'Cerignola',
    slug: 'cerignola',
    region: 'Puglia',
    province: 'Foggia',
    provinceCode: 'FG',
    lat: 41.2691,
    lng: 15.7716,
    altNames: [],
    isActive: true,
    sortOrder: 94,
  },
  {
    id: 95,
    name: 'Bitonto',
    slug: 'bitonto',
    region: 'Puglia',
    province: 'Bari',
    provinceCode: 'BA',
    lat: 41.1361,
    lng: 16.7789,
    altNames: [],
    isActive: true,
    sortOrder: 95,
  },
  {
    id: 96,
    name: 'Savona',
    slug: 'savona',
    region: 'Liguria',
    province: 'Savona',
    provinceCode: 'SV',
    lat: 44.3091,
    lng: 8.4772,
    altNames: [],
    isActive: true,
    sortOrder: 96,
  },
  {
    id: 97,
    name: 'Avellino',
    slug: 'avellino',
    region: 'Campania',
    province: 'Avellino',
    provinceCode: 'AV',
    lat: 40.9143,
    lng: 14.788,
    altNames: [],
    isActive: true,
    sortOrder: 97,
  },
  {
    id: 98,
    name: 'Ercolano',
    slug: 'ercolano',
    region: 'Campania',
    province: 'Napoli',
    provinceCode: 'NA',
    lat: 40.8028,
    lng: 14.3926,
    altNames: ['Herculaneum'],
    isActive: true,
    sortOrder: 98,
  },
  {
    id: 99,
    name: 'Rho',
    slug: 'rho',
    region: 'Lombardia',
    province: 'Milano',
    provinceCode: 'MI',
    lat: 45.516,
    lng: 9.083,
    altNames: [],
    isActive: true,
    sortOrder: 99,
  },
  {
    id: 100,
    name: 'Caltanissetta',
    slug: 'caltanissetta',
    region: 'Sicilia',
    province: 'Caltanissetta',
    provinceCode: 'CL',
    lat: 37.4864,
    lng: 14.0629,
    altNames: [],
    isActive: true,
    sortOrder: 100,
  },
  {
    id: 101,
    name: 'Caserta',
    slug: 'caserta',
    region: 'Campania',
    province: 'Caserta',
    provinceCode: 'CE',
    lat: 41.0687,
    lng: 14.3344,
    altNames: [],
    isActive: true,
    sortOrder: 101,
  },
  {
    id: 102,
    name: 'Benevento',
    slug: 'benevento',
    region: 'Campania',
    province: 'Benevento',
    provinceCode: 'BN',
    lat: 41.1296,
    lng: 14.783,
    altNames: [],
    isActive: true,
    sortOrder: 102,
  },
  {
    id: 103,
    name: 'Matera',
    slug: 'matera',
    region: 'Basilicata',
    province: 'Matera',
    provinceCode: 'MT',
    lat: 40.6667,
    lng: 16.6,
    altNames: [],
    isActive: true,
    sortOrder: 103,
  },
  {
    id: 104,
    name: 'Crotone',
    slug: 'crotone',
    region: 'Calabria',
    province: 'Crotone',
    provinceCode: 'KR',
    lat: 39.0833,
    lng: 17.1167,
    altNames: [],
    isActive: true,
    sortOrder: 104,
  },
  {
    id: 105,
    name: 'Vibo Valentia',
    slug: 'vibo-valentia',
    region: 'Calabria',
    province: 'Vibo Valentia',
    provinceCode: 'VV',
    lat: 38.677,
    lng: 16.1,
    altNames: [],
    isActive: true,
    sortOrder: 105,
  },
  {
    id: 106,
    name: 'Enna',
    slug: 'enna',
    region: 'Sicilia',
    province: 'Enna',
    provinceCode: 'EN',
    lat: 37.567,
    lng: 14.2796,
    altNames: [],
    isActive: true,
    sortOrder: 106,
  },
  {
    id: 107,
    name: 'Mazara del Vallo',
    slug: 'mazara-del-vallo',
    region: 'Sicilia',
    province: 'Trapani',
    provinceCode: 'TP',
    lat: 37.6497,
    lng: 12.5873,
    altNames: [],
    isActive: true,
    sortOrder: 107,
  },
  {
    id: 108,
    name: 'Agrigento',
    slug: 'agrigento',
    region: 'Sicilia',
    province: 'Agrigento',
    provinceCode: 'AG',
    lat: 37.3111,
    lng: 13.5764,
    altNames: [],
    isActive: true,
    sortOrder: 108,
  },
  {
    id: 109,
    name: 'Alcamo',
    slug: 'alcamo',
    region: 'Sicilia',
    province: 'Trapani',
    provinceCode: 'TP',
    lat: 38.0369,
    lng: 12.9577,
    altNames: [],
    isActive: true,
    sortOrder: 109,
  },
  {
    id: 110,
    name: 'Favara',
    slug: 'favara',
    region: 'Sicilia',
    province: 'Agrigento',
    provinceCode: 'AG',
    lat: 37.3061,
    lng: 13.5865,
    altNames: [],
    isActive: true,
    sortOrder: 110,
  },
  {
    id: 111,
    name: 'Oristano',
    slug: 'oristano',
    region: 'Sardegna',
    province: 'Oristano',
    provinceCode: 'OR',
    lat: 39.903,
    lng: 8.5917,
    altNames: [],
    isActive: true,
    sortOrder: 111,
  },
  {
    id: 112,
    name: 'Iglesias',
    slug: 'iglesias',
    region: 'Sardegna',
    province: 'Sud Sardegna',
    provinceCode: 'SU',
    lat: 39.3058,
    lng: 8.5486,
    altNames: [],
    isActive: true,
    sortOrder: 112,
  },
  {
    id: 113,
    name: 'Nuoro',
    slug: 'nuoro',
    region: 'Sardegna',
    province: 'Nuoro',
    provinceCode: 'NU',
    lat: 40.3217,
    lng: 9.3264,
    altNames: [],
    isActive: true,
    sortOrder: 113,
  },
  {
    id: 114,
    name: 'Olbia',
    slug: 'olbia',
    region: 'Sardegna',
    province: 'Olbia-Tempio',
    provinceCode: 'OT',
    lat: 40.9234,
    lng: 9.4961,
    altNames: [],
    isActive: true,
    sortOrder: 114,
  },
  {
    id: 115,
    name: 'Legnano',
    slug: 'legnano',
    region: 'Lombardia',
    province: 'Milano',
    provinceCode: 'MI',
    lat: 45.5908,
    lng: 8.9136,
    altNames: [],
    isActive: true,
    sortOrder: 115,
  },
  {
    id: 116,
    name: 'Lodi',
    slug: 'lodi',
    region: 'Lombardia',
    province: 'Lodi',
    provinceCode: 'LO',
    lat: 45.3142,
    lng: 9.5031,
    altNames: [],
    isActive: true,
    sortOrder: 116,
  },
  {
    id: 117,
    name: 'Lecco',
    slug: 'lecco',
    region: 'Lombardia',
    province: 'Lecco',
    provinceCode: 'LC',
    lat: 45.8566,
    lng: 9.3977,
    altNames: [],
    isActive: true,
    sortOrder: 117,
  },
  {
    id: 118,
    name: 'La Maddalena',
    slug: 'la-maddalena',
    region: 'Sardegna',
    province: 'Sassari',
    provinceCode: 'SS',
    lat: 41.2,
    lng: 9.4,
    altNames: ['Maddalena'],
    isActive: true,
    sortOrder: 118,
  },
  {
    id: 119,
    name: 'Viareggio',
    slug: 'viareggio',
    region: 'Toscana',
    province: 'Lucca',
    provinceCode: 'LU',
    lat: 43.8636,
    lng: 10.2559,
    altNames: [],
    isActive: true,
    sortOrder: 119,
  },
  {
    id: 120,
    name: 'Siena',
    slug: 'siena',
    region: 'Toscana',
    province: 'Siena',
    provinceCode: 'SI',
    lat: 43.3186,
    lng: 11.3308,
    altNames: [],
    isActive: true,
    sortOrder: 120,
  },
  {
    id: 121,
    name: 'Pisa',
    slug: 'pisa',
    region: 'Toscana',
    province: 'Pisa',
    provinceCode: 'PI',
    lat: 43.715,
    lng: 10.401,
    altNames: [],
    isActive: true,
    sortOrder: 121,
  },
  {
    id: 122,
    name: 'Cortona',
    slug: 'cortona',
    region: 'Toscana',
    province: 'Arezzo',
    provinceCode: 'AR',
    lat: 43.2599,
    lng: 11.996,
    altNames: [],
    isActive: true,
    sortOrder: 122,
  },
  {
    id: 123,
    name: 'Cassino',
    slug: 'cassino',
    region: 'Lazio',
    province: 'Frosinone',
    provinceCode: 'FR',
    lat: 41.4931,
    lng: 13.8336,
    altNames: [],
    isActive: true,
    sortOrder: 123,
  },
  {
    id: 124,
    name: 'Belluno',
    slug: 'belluno',
    region: 'Veneto',
    province: 'Belluno',
    provinceCode: 'BL',
    lat: 46.1426,
    lng: 12.2167,
    altNames: [],
    isActive: true,
    sortOrder: 124,
  },
  {
    id: 125,
    name: 'Sondrio',
    slug: 'sondrio',
    region: 'Lombardia',
    province: 'Sondrio',
    provinceCode: 'SO',
    lat: 46.1699,
    lng: 9.8736,
    altNames: [],
    isActive: true,
    sortOrder: 125,
  },
  {
    id: 126,
    name: 'Gorizia',
    slug: 'gorizia',
    region: 'Friuli-Venezia Giulia',
    province: 'Gorizia',
    provinceCode: 'GO',
    lat: 45.9428,
    lng: 13.6176,
    altNames: [],
    isActive: true,
    sortOrder: 126,
  },
  {
    id: 127,
    name: 'Verbania',
    slug: 'verbania',
    region: 'Piemonte',
    province: 'Verbano-Cusio-Ossola',
    provinceCode: 'VB',
    lat: 45.9225,
    lng: 8.5516,
    altNames: [],
    isActive: true,
    sortOrder: 127,
  },
  {
    id: 128,
    name: 'Rieti',
    slug: 'rieti',
    region: 'Lazio',
    province: 'Rieti',
    provinceCode: 'RI',
    lat: 42.4046,
    lng: 12.8599,
    altNames: [],
    isActive: true,
    sortOrder: 128,
  },
  {
    id: 129,
    name: 'Isernia',
    slug: 'isernia',
    region: 'Molise',
    province: 'Isernia',
    provinceCode: 'IS',
    lat: 41.5958,
    lng: 14.2386,
    altNames: [],
    isActive: true,
    sortOrder: 129,
  },
  {
    id: 130,
    name: 'Chioggia',
    slug: 'chioggia',
    region: 'Veneto',
    province: 'Venezia',
    provinceCode: 'VE',
    lat: 45.2156,
    lng: 12.2553,
    altNames: [],
    isActive: true,
    sortOrder: 130,
  },
  {
    id: 131,
    name: 'Martina Franca',
    slug: 'martina-franca',
    region: 'Puglia',
    province: 'Taranto',
    provinceCode: 'TA',
    lat: 40.7078,
    lng: 17.3289,
    altNames: [],
    isActive: true,
    sortOrder: 131,
  },
  {
    id: 132,
    name: 'Fano',
    slug: 'fano',
    region: 'Marche',
    province: 'Pesaro e Urbino',
    provinceCode: 'PU',
    lat: 43.8404,
    lng: 13.0156,
    altNames: [],
    isActive: true,
    sortOrder: 132,
  },
  {
    id: 133,
    name: 'Senigallia',
    slug: 'senigallia',
    region: 'Marche',
    province: 'Ancona',
    provinceCode: 'AN',
    lat: 43.7134,
    lng: 13.2078,
    altNames: [],
    isActive: true,
    sortOrder: 133,
  },
  {
    id: 134,
    name: 'Vittoria',
    slug: 'vittoria',
    region: 'Sicilia',
    province: 'Ragusa',
    provinceCode: 'RG',
    lat: 36.9465,
    lng: 14.5295,
    altNames: [],
    isActive: true,
    sortOrder: 134,
  },
  {
    id: 135,
    name: 'Bagheria',
    slug: 'bagheria',
    region: 'Sicilia',
    province: 'Palermo',
    provinceCode: 'PA',
    lat: 38.0741,
    lng: 13.52,
    altNames: [],
    isActive: true,
    sortOrder: 135,
  },
  {
    id: 136,
    name: "Cava de' Tirreni",
    slug: 'cava-de-tirreni',
    region: 'Campania',
    province: 'Salerno',
    provinceCode: 'SA',
    lat: 40.7236,
    lng: 14.6167,
    altNames: ['Cava de Tirreni'],
    isActive: true,
    sortOrder: 136,
  },
  {
    id: 137,
    name: 'Manfredonia',
    slug: 'manfredonia',
    region: 'Puglia',
    province: 'Foggia',
    provinceCode: 'FG',
    lat: 41.6278,
    lng: 15.9111,
    altNames: [],
    isActive: true,
    sortOrder: 137,
  },
  {
    id: 138,
    name: 'Sanremo',
    slug: 'sanremo',
    region: 'Liguria',
    province: 'Imperia',
    provinceCode: 'IM',
    lat: 43.8159,
    lng: 7.7764,
    altNames: ['San Remo'],
    isActive: true,
    sortOrder: 138,
  },
  {
    id: 139,
    name: 'Aversa',
    slug: 'aversa',
    region: 'Campania',
    province: 'Caserta',
    provinceCode: 'CE',
    lat: 40.9756,
    lng: 14.2126,
    altNames: [],
    isActive: true,
    sortOrder: 139,
  },
];
