-- Auto-generated by scripts/generate-cities-sql.js
-- Inserts or upserts cities into public.cities table

INSERT INTO public.cities (name, slug, region, province, "provinceCode", lat, lng, "altNames", "isActive", "sortOrder", "updatedAt")
VALUES
  ('Rome', 'rome', 'Lazio', 'Roma', 'RM', NULL, NULL, ARRAY['Roma']::TEXT[], true, 1, CURRENT_TIMESTAMP),
  ('Milan', 'milan', 'Lombardia', 'Milano', 'MI', NULL, NULL, ARRAY['Milano']::TEXT[], true, 2, CURRENT_TIMESTAMP),
  ('Naples', 'naples', 'Campania', 'Napoli', 'NA', NULL, NULL, ARRAY['Napoli']::TEXT[], true, 3, CURRENT_TIMESTAMP),
  ('Turin', 'turin', 'Piemonte', 'Torino', 'TO', NULL, NULL, ARRAY['Torino']::TEXT[], true, 4, CURRENT_TIMESTAMP),
  ('Palermo', 'palermo', 'Sicilia', 'Palermo', 'PA', NULL, NULL, ARRAY[]::TEXT[], true, 5, CURRENT_TIMESTAMP)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  region = EXCLUDED.region,
  province = EXCLUDED.province,
  "provinceCode" = EXCLUDED."provinceCode",
  lat = EXCLUDED.lat,
  lng = EXCLUDED.lng,
  "altNames" = EXCLUDED."altNames",
  "isActive" = EXCLUDED."isActive",
  "sortOrder" = EXCLUDED."sortOrder",
  "updatedAt" = CURRENT_TIMESTAMP;
